language: ruby
sudo: false

script:
  - bundle exec rake spec SPEC_OPTS='--format documentation'

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - RSPEC_VERSION=2.14
  - RSPEC_VERSION=3.2

matrix:
  exclude:
    - rvm: 1.8.7
      env: RSPEC_VERSION=3.2

notifications:
  email: false
